/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    antlr
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(project(":org.sirius.common"))
    implementation(project(":org.sirius.sdk"))

    implementation("org.antlr:antlr4-runtime:4.13.0")
    antlr("org.antlr:antlr4:4.13.0")

    implementation("org.ow2.asm:asm:9.4")
}

tasks.generateGrammarSource {
    arguments = listOf("-visitor", "-listener")
}

/*
plugins {
    id("org.sirius.java-conventions")
}

description = "org.sirius.frontend"
*/
