/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
}

subprojects {
    apply(plugin = "java")
    repositories{
        mavenCentral()
    }
    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }
    dependencies {
        testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.2")
        testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.2")
        testImplementation("org.hamcrest:hamcrest:2.2")
        testImplementation("org.mockito:mockito-core:4.1.0")
        testImplementation("org.mockito:mockito-junit-jupiter:4.1.0")

    }
}

/*
plugins {
    java {
//        sourceCompatibility = JavaVersion.VERSION_17
    }
//    kotlin("jvm")
    id("org.sirius.java-conventions")
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.2")
    testImplementation("org.hamcrest:hamcrest:2.2")
}

description = "org.sirius.common"
*/
