/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "parent"
include(":org.sirius.backend.jvm")
include(":org.sirius.runtime")
include(":org.sirius.compiler")
include(":org.sirius.sdk")
include(":org.sirius.backend.core")
include(":org.sirius.common")
include(":org.sirius.frontend")
