/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    implementation(project(":org.sirius.common"))
    implementation(project(":org.sirius.frontend"))
    implementation(project(":org.sirius.backend.core"))
    implementation(project(":org.sirius.backend.jvm"))
    implementation(project(":org.sirius.runtime"))

    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.2")
    testImplementation("org.mockito:mockito-core:4.1.0")
    testImplementation("org.mockito:mockito-junit-jupiter:4.1.0")
    testImplementation("org.hamcrest:hamcrest:2.2")

//    implementation(project(":org.sirius.runtime"))
    implementation("org.ow2.asm:asm:9.4")
}

/*

plugins {
    id("org.sirius.java-conventions")
}

dependencies {
    api(project(":org.sirius.common"))
    api(project(":org.sirius.frontend"))
    api(project(":org.sirius.backend.core"))
    api(project(":org.sirius.backend.jvm"))
    api(project(":org.sirius.runtime"))
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.2")
    testImplementation("org.mockito:mockito-core:4.1.0")
    testImplementation("org.mockito:mockito-junit-jupiter:4.1.0")
    testImplementation("org.hamcrest:hamcrest:2.2")
}

description = "org.sirius.compiler"
*/
