/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.2")
    testImplementation("org.hamcrest:hamcrest:2.2")
}

/*
plugins {
    id("org.sirius.java-conventions")
}
description = "org.sirius.sdk"
*/
