/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    implementation(project(":org.sirius.common"))
    implementation(project(":org.sirius.frontend"))
}

/*

plugins {
    id("org.sirius.java-conventions")
}
description = "org.sirius.backend.core"
*/
